Traceback (most recent call last):
  File "/home/hzhu/project/EMNLP_BLA/BLIP/bla_utils.py", line 26, in read_json_file
    json_file = open(file_path, "r")
FileNotFoundError: [Errno 2] No such file or directory: '/home/hzhu/project/EMNLP_BLA/BLIP/datasets/BLA/original/finetune/finetune_random/rc/test.json'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/hzhu/project/EMNLP_BLA/BLIP/test_blip2_bla.py", line 371, in <module>
    evaluate_vqa(args)
  File "/home/hzhu/project/EMNLP_BLA/BLIP/test_blip2_bla.py", line 78, in evaluate_vqa
    items = utils.read_json_file(args.file_path)
  File "/home/hzhu/project/EMNLP_BLA/BLIP/bla_utils.py", line 29, in read_json_file
    if json_file:
NameError: name 'json_file' is not defined